name: Deploy Fake 
on: 
    workflow_call: 
        inputs: 
            ambiente:
                type: string
                default: "dev"
                description: "Ambiente onde vai ser feito o deploy"
jobs: 
    deploy-fake:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de desenvolvimento ${{ inputs.ambiente }}"
