name: Deploy Fake 
on: 
    workflow_call: 
        secrets: 
            ambiente:
                description: "Ambiente onde vai ser feito o deploy"
jobs: 
    deploy-fake:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{ secrets.ambiente }}"
