name: Workflow_call
on: 
    workflow_call: 
       # Para usar com parametro
        # secrets: 
       #     ambiente:
       #         description: "Ambiente onde vai ser feito o deploy"
jobs: 
    deploy-fake:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{ secrets.AMBIENTE_ENTREGA }}"
            - name:
              run: "curl -X POST https://webhook.site/e2a61dd6-2c80-4974-a4a2-68e9991bb16a -d '{ ambniente: ${{ secrets.AMBIENTE_ENTREGA }}}'"
